baseurl = "https://blog.nathanv.me/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
googleAnalytics = "UA-91853319-4"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true
    noreferrerLinks = true

[params]
  contentTypeName = "posts"
  defaultTheme = "dark"
  showMenuItems = 2
  showReadingTime = true
  toc = true
  rssFullText = true

[languages]
  [languages.en]
    title = "Nathan Vaughn"
    description = "Adventures in programming and tech"
    subtitle = "Adventures in programming and tech"
    # default open graph image
    images = ["img/favicon.png"]
    keywords = ["programming", "tech", "Nathan", "Vaughn", "blog"]

    [languages.en.params.logo]
      logoText = "nathanv@blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "Homepage"
        name = "Homepage"
        weight = 10
        url = "https://nathanv.me"

      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        weight = 20
        url = "https://github.com/NathanVaughn"
