baseurl = "https://blog.nathanv.me/"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5
googleAnalytics = "UA-91853319-4"

[markup]
  defaultMarkdownHandler = "blackfriday"
  [markup.blackFriday]
    hrefTargetBlank = true
    noreferrerLinks = true

[params]
  contentTypeName = "posts"
  themeColor = "red"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = true
  showReadingTime = true

[languages]
  [languages.en]
    title = "Nathan Vaughn"
    description = "Adventures in programming and tech"
    subtitle = "Adventures in programming and tech"
    # default open graph image
    images = ["img/favicon.png"]
    keywords = ["programming", "tech"]
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Nathan Vaughn"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "Homepage"
        name = "Homepage"
        weight = 10
        url = "https://nathanv.me"

      [[languages.en.menu.main]]
        identifier = "github"
        name = "GitHub"
        weight = 20
        url = "https://github.com/NathanVaughn"
