# general settings
baseurl         = "/"
languageCode    = "en-us"
theme           = "hugo-theme-hello-friend-mod"
# enableGitInfo   = true
enableRobotsTXT = true

[pagination]
  pagerSize = 5

# better resampling algorithm
[imaging]
  quality = 95
  resampleFilter = "Lanczos"

# markdown settings
[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.extensions]
  footnote = true

[markup.goldmark.renderer]
  # needed for superscript
  unsafe = true

[markup.highlight]
  lineNos = true
  lineNumbersInTable = false
  anchorLineNos = true
  # https://xyproto.github.io/splash/docs/all.html
  style = "vulcan"

# theme parameters
[params]
  contentTypeName = "posts"
  defaultTheme    = "dark"
  showMenuItems   = 2
  showReadingTime = true
  toc             = true
  rssFullText     = true
  # custom favicon
  favicon = "https://nathanv.me/img/theme-colors/green.png"
  # default open graph image
  images = ["img/opg.png"]

[privacy]
  [privacy.youtube]
    privacyEnhanced = true

[languages]
  [languages.en]
      title       = "nathanv@blog"
      copyright   = '<span>Written by a <a href="https://nathanv.me">human</a>, for humans</span>'

    [languages.en.params]
      keywords    = ["programming", "tech", "Nathan", "Vaughn", "blog"]
      description = "Adventures in programming and tech"
      subtitle    = "Adventures in programming and tech"
      lastModDisplay = "Last Modified:"

    # logo parameters
    [languages.en.params.logo]
      logoText     = "nathanv@blog"
      logoHomeLink = "/"

  # extra links
  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "Homepage"
      name       = "Homepage"
      weight     = 10
      url        = "https://nathanv.me"

    [[languages.en.menu.main]]
      identifier = "links"
      name       = "Links"
      weight     = 20
      url        = "https://links.nathanv.me/"
