# general settings
baseurl      = "/"
languageCode = "en-us"
theme        = "hugo-theme-hello-friend-mod"
# enableGitInfo   = true
enableRobotsTXT = true
# increase timeout due to image processing
timeout = "120s"

[pagination]
  pagerSize = 5

# better resampling algorithm
[imaging]
  quality        = 95
  resampleFilter = "Lanczos"

# markdown settings
[markup]
  defaultMarkdownHandler = "goldmark"

[markup.goldmark]
[markup.goldmark.extensions]
  footnote = true

[markup.goldmark.renderer]
  # needed for superscript
  unsafe = true

[markup.goldmark.parser]
  # prevent images from being wrapped with a paragraph
  wrapStandAloneImageWithinParagraph = false

[markup.highlight]
  lineNos            = true
  lineNumbersInTable = false
  anchorLineNos      = true
  # https://xyproto.github.io/splash/docs/all.html
  # was using vulcan before, comments were borderline unreadable
  style = "doom-one"

[outputs]
  # disable rss except for homepage
  home     = ['html', 'rss']
  section  = ['html']
  taxonomy = ['html']
  term     = ['html']

# theme parameters
[params]
  contentTypeName = "posts"
  defaultTheme    = "dark"
  showMenuItems   = 2
  showReadingTime = true
  toc             = true
  rssFullText     = false # as much as I want this to work, it's a huge pain to support
  # custom favicon
  favicon = "https://nathanv.me/img/theme-colors/green.png"
  # default open graph image
  images = ["img/opg.png"]

[privacy]
[privacy.youtube]
  privacyEnhanced = true

[params.author]
  # used for RSS
  name  = 'Nathan Vaughn'

[languages]
[languages.en]
  title     = "nathanv@blog"
  copyright = 'Written by a human, for humans'

[languages.en.params]
  keywords       = ["programming", "tech", "Nathan", "Vaughn", "blog"]
  description    = "Adventures in programming and tech"
  subtitle       = "Adventures in programming and tech"
  lastModDisplay = "Last Modified:"

# logo parameters
[languages.en.params.logo]
  logoText     = "nathanv@blog"
  logoHomeLink = "/"

# extra links
[languages.en.menu]
[[languages.en.menu.main]]
  identifier = "Homepage"
  name       = "Homepage"
  weight     = 10
  url        = "https://nathanv.me"

[[languages.en.menu.main]]
  identifier = "links"
  name       = "Links"
  weight     = 20
  url        = "https://links.nathanv.me/"
