version: '3'

services:
  app:
    build: .
    privileged: true
    restart: unless-stopped
    volumes:
      - app_data:/usr/local/ppbe/db_local/
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone

volumes:
  app_data:
    driver: local
