name: Build

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup NPM
      uses: actions/setup-node@v2.1.3

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2

    - name: Cache Node Modules
      uses: actions/cache@v2
      id: cache-npm
      with:
        path: node_modules
        key: npm-${{ hashFiles('**/package-lock.json') }}

    - name: Install Node Dependencies
      if: steps.cache-npm.outputs.cache-hit != 'true'
      run: npm install

    - name: Build Site
      run: npm run build

    - name: Deploy Site
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public

    - name: Purge Cache
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}

    - name: Load Site
      run: curl $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2-) --location --output /dev/null

    - name: Update Sitemap
      run: curl http://www.google.com/ping?sitemap=https://$(echo $GITHUB_REPOSITORY | cut -d "/" -f 2-)/sitemap.xml