name: Test

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: npm

      - name: Install Dependencies
        run: npm install

      - name: Check formatting
        run: npm run format:check

      - name: Build Site
        run: npx hugo
