name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@master
      with:
        hugo-version: '0.57'
    - name: Build Site
      run: hugo --gc --cleanDestinationDir
    - name: Deploy site
      uses: peaceiris/actions-gh-pages@master
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
