name: Build

on:
  push:
    branches:
    - master

jobs:
  beautify:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
    - name: Install Node
      uses: actions/setup-node@master
    - name: Install Dependencies
      run: npm install
    - name: Beautify Markdown
      run: npm run beautify
    - name: Commit Changes
      uses: elstudio/actions-js-build/commit@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@master
    - name: Build Site
      run: hugo --gc --cleanDestinationDir
    - name: Deploy Site
      uses: peaceiris/actions-gh-pages@master
      if: success()
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./public
    - name: Purge Cache
      uses: nathanvaughn/actions-cloudflare-purge@master
      if: success()
      env:
        CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
        CLOUDFLARE_AUTH_KEY: ${{ secrets.CLOUDFLARE_AUTH_KEY }}
    - name: Load Site
      run: curl $(echo $GITHUB_REPOSITORY | cut -d "/" -f 2-) --location --output /dev/null